### PR TITLE
changes for multiuser on multidisplay

### PR DESCRIPTION
**Pull request by pachecoberlin**

### CODE REVIEW

**Comment by KonstaT** [comment]
Please include an explanation what this PR intends to do and why.

Also consider splitting this up into separate commits as e.g. ADB related changes or enabling bluetooth by default have no part in this.

Display resolution/density changes or configuration for some specific USB touchscreen are probably also not something that suits everyone considering this project should support devices running different display hardware setup. Also cleanup commented out parts and unnecessary repetition (setting a property three times and copying a configuration file several times).

**Comment by pachecoberlin** [comment]
Hey KonstaT,
this was by mistake the PR should have my forks branch as target.
Anyway i wanted to contact you, since i have trouble connecting via adb and/or ssh to my rpi5 with AAOS 15.
How can i:

- enable adb over tcpip by default (most interesting point for me)
- enable adb by default
- enable ssh by default

If you have any suggestion i would greatly appreciate it. If i shall rather write you an email i can do so.

Kind regards,
pacheco

[pacheco@gmx.de](mailto:pacheco@gmx.de)

**Comment by KonstaT** [comment]
To enable ADB over network (TCP), simply add following to device.mk:
```
PRODUCT_VENDOR_PROPERTIES += \
    persist.adb.tcp.port=5555
```

ADB is already enabled by default on `userdebug` builds.

SSH is not part of Raspberry Vanilla project. You can look into including e.g. https://github.com/lineage-rpi/android_external_openssh/tree/lineage-22 in your builds.

**Comment by pachecoberlin** [comment]
Thank you very much KostaKANG!

I hope i don't bother you with some more questions...

While i love problem solving short answers, 
How would i find this vendor property by myself, must i go through the adb daemons source code or is there another way?
How can i extend my knowledge on building AOSP, only on source.android.com or are there any courses or something you can recommend? 

I actually have another main issue and maybe you have any hint on that one. I have two touchscreens connected to rpi5 with AAOS15 and multiuser on multidisplays enabled. The problem now is the touches on both screens are executed only on the first screen, so that i cannot control the sceond screen.

**Comment by KonstaT** [comment]
> While i love problem solving short answers, How would i find this vendor property by myself, must i go through the adb daemons source code or is there another way? How can i extend my knowledge on building AOSP, only on source.android.com or are there any courses or something you can recommend?

https://cs.android.com/ helps if you know what you're looking for. I'm not aware of any documentation that covers e.g. system properties that also tend to change over time. Source code is the documentation.

**Pull request closed without merging**
