### PR TITLE
32bit arm support and enable background blur

### PR DESCRIPTION
**Pull request by dattrax**
blur was missing so some apps didn't render as expected

Fix the 32bit build

### CODE REVIEW

**Comment by KonstaT** [comment]
Please specify what is the purpose of this patch set (32-bit support).
https://github.com/raspberry-vanilla/android_device_brcm_rpi5/pull/1
https://github.com/raspberry-vanilla/android_external_ffmpeg_codec2/pull/1
https://github.com/raspberry-vanilla/android_external_ffmpeg/pull/1

Realistically the future approach is to move to 64-bit only target on future Android versions (Android 15) rather than keep support for 32-bit.

**Comment by dattrax** [comment]
GTV builds use 32bits for the moment, so I was integrating against that and found some stuff didn't work with native 64 (like incompatibility splash screens)

**Comment by KonstaT** [comment]
GTV? What does this abbreviation mean? Is that something that Raspberry Vanilla project should support in the first place?

I think the way forward is to strip any remaining 32-bit support and move to 64-bit only target maybe with the next Android version.

**Comment by dattrax** [comment]
GTV is expected to replace ATV

there’s a good article from January 2024 on android authority web site on GTV vs ATV.

**Comment by KonstaT** [comment]
Why not then just say Google TV. I don't consider Google a curse word. ;)

But yeah, I'm not entirely sure about the reasoning. Google TV is proprietary feature set on top of Android TV. Purpose of this project is to provide AOSP build targets for Raspberry Pi and any proprietary Google services are not part of that. I'm sure there will also be 64-bit Google TV devices released in the future if not already exist. There's also been reports someone managing to install at least the Google TV launcher on existing 32/64-bit multilib builds (https://source.android.com/docs/setup/create/64-bit-builds). Are you sure this requires 32-bit only build target as this PR doesn't even quite add one?

**Comment by dattrax** [comment]
I do have 64bit builds available of GoogleTV, but for comparison, its useful to have a 32bit build also.

Whilst philosophically you can argue 32bit is dead, its not for my use.  These set of pull requests do not alter the 64bit target, but make it easier for the switch, should you want to.  The background blur patch is not related to the bit width and is applicable for both.

**Comment by KonstaT** [comment]
As mentioned earlier, current configuration produces 32/64-bit multilib builds. Plan forward is to move to 64-bit only builds. In any case, this PR is incomplete if the intention was to add 32-bit only build target.

I tested the window blur and it has a negative impact on graphics performance. As documented (https://source.android.com/docs/core/display/window-blurs), "Graphics performance: Devices with less performant GPUs might choose not to support window blurs".

**Pull request closed without merging**
